
package com.net.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Timbrado_CfdiSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TimbradoCfdiSoap {


    /**
     * 
     * @param xml
     * @param identificador
     * @return
     *     returns com.net.wsdl.TimbradoCfdi
     */
    @WebMethod(operationName = "Timbrar", action = "http://tempuri.org/Timbrar")
    @WebResult(name = "TimbrarResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Timbrar", targetNamespace = "http://tempuri.org/", className = "com.net.wsdl.Timbrar")
    @ResponseWrapper(localName = "TimbrarResponse", targetNamespace = "http://tempuri.org/", className = "com.net.wsdl.TimbrarResponse")
    public TimbradoCfdi timbrar(
        @WebParam(name = "identificador", targetNamespace = "http://tempuri.org/")
        String identificador,
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        String xml);

}
