
package com.b1soft.cancelacion.wsdl;

import clier.Constantes;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CancelacionCfdi", targetNamespace = "http://servidor.b1soft.com/", wsdlLocation = "http://localhost:8282/b1cancelacion/CancelacionCfdi?wsdl")
public class CancelacionCfdi_Service
    extends Service
{

    private final static URL CANCELACIONCFDI_WSDL_LOCATION;
    private final static WebServiceException CANCELACIONCFDI_EXCEPTION;
    private final static QName CANCELACIONCFDI_QNAME = new QName("http://servidor.b1soft.com/", "CancelacionCfdi");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            System.out.println("\t\t" + Constantes.WSDL_CANCELACION);
            url = new URL(Constantes.WSDL_CANCELACION);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CANCELACIONCFDI_WSDL_LOCATION = url;
        CANCELACIONCFDI_EXCEPTION = e;
    }

    public CancelacionCfdi_Service() {
        super(__getWsdlLocation(), CANCELACIONCFDI_QNAME);
    }

    public CancelacionCfdi_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CANCELACIONCFDI_QNAME, features);
    }

    public CancelacionCfdi_Service(URL wsdlLocation) {
        super(wsdlLocation, CANCELACIONCFDI_QNAME);
    }

    public CancelacionCfdi_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CANCELACIONCFDI_QNAME, features);
    }

    public CancelacionCfdi_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CancelacionCfdi_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CancelacionCfdiWsdl
     */
    @WebEndpoint(name = "CancelacionCfdiWsdlPort")
    public CancelacionCfdiWsdl getCancelacionCfdiWsdlPort() {
        return super.getPort(new QName("http://servidor.b1soft.com/", "CancelacionCfdiWsdlPort"), CancelacionCfdiWsdl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CancelacionCfdiWsdl
     */
    @WebEndpoint(name = "CancelacionCfdiWsdlPort")
    public CancelacionCfdiWsdl getCancelacionCfdiWsdlPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servidor.b1soft.com/", "CancelacionCfdiWsdlPort"), CancelacionCfdiWsdl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CANCELACIONCFDI_EXCEPTION!= null) {
            throw CANCELACIONCFDI_EXCEPTION;
        }
        return CANCELACIONCFDI_WSDL_LOCATION;
    }

}
