
package com.b1soft.servidor.wsdl;

import clier.Constantes;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLStreamHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TimbradoCfdi", targetNamespace = "http://wsdl.servidor.b1soft.com/", wsdlLocation = "http://localhost:8080/b1timbre_compl_v4_0_4/TimbradoCfdi?wsdl")
public class TimbradoCfdi_Service
    extends Service
{

    private final static URL TIMBRADOCFDI_WSDL_LOCATION;
    private final static WebServiceException TIMBRADOCFDI_EXCEPTION;
    private final static QName TIMBRADOCFDI_QNAME = new QName("http://wsdl.servidor.b1soft.com/", "TimbradoCfdi");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            System.out.println("\t\t" + Constantes.WSDL);
            //url = new URL(Constantes.WSDL);
            url = new URL(null, Constantes.WSDL, new URLStreamHandler() {
                protected URLConnection openConnection(URL url) throws IOException {
                    // The url is the parent of this stream handler, so must create clone  
                    URL clone = new URL(url.toString());
                    URLConnection connection = clone.openConnection();
                    // If you cast to HttpURLConnection, you can set redirects  
                    // connection.setInstanceFollowRedirects (false); // no redirs  
                    connection.setConnectTimeout(Constantes.TIMEOUT * 1000);
                    connection.setReadTimeout(Constantes.TIMEOUT * 1000);
                    // Custom header  
                    connection.addRequestProperty("Developer-Mood", "ClierB1Timbre");
                    return connection;
                }
            });
//            url = new URL("http://localhost:8080/b1timbre_compl_v4_0_4/TimbradoCfdi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        } catch (IOException ex) {
            Logger.getLogger(com.b1soft.timbrado.wsdl.TimbradoCfdi_Service.class.getName()).log(Level.SEVERE, null, ex);
        }
        TIMBRADOCFDI_WSDL_LOCATION = url;
        TIMBRADOCFDI_EXCEPTION = e;
    }

    public TimbradoCfdi_Service() {
        super(__getWsdlLocation(), TIMBRADOCFDI_QNAME);
    }

    public TimbradoCfdi_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIMBRADOCFDI_QNAME, features);
    }

    public TimbradoCfdi_Service(URL wsdlLocation) {
        super(wsdlLocation, TIMBRADOCFDI_QNAME);
    }

    public TimbradoCfdi_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIMBRADOCFDI_QNAME, features);
    }

    public TimbradoCfdi_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimbradoCfdi_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TimbradoCfdiWsdl
     */
    @WebEndpoint(name = "TimbradoCfdiWsdlPort")
    public TimbradoCfdiWsdl getTimbradoCfdiWsdlPort() {
        return super.getPort(new QName("http://wsdl.servidor.b1soft.com/", "TimbradoCfdiWsdlPort"), TimbradoCfdiWsdl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TimbradoCfdiWsdl
     */
    @WebEndpoint(name = "TimbradoCfdiWsdlPort")
    public TimbradoCfdiWsdl getTimbradoCfdiWsdlPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsdl.servidor.b1soft.com/", "TimbradoCfdiWsdlPort"), TimbradoCfdiWsdl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIMBRADOCFDI_EXCEPTION!= null) {
            throw TIMBRADOCFDI_EXCEPTION;
        }
        return TIMBRADOCFDI_WSDL_LOCATION;
    }

}
